### PR TITLE
Introduction of Right-hand nav feature

### PR DESCRIPTION
**Pull request by TrebBrennan**
I think we’ll need to have a good look at main content area width
(currently 9 col)

### CODE REVIEW

**Comment by klepas** [comment]
Nice @TrebBrennan — looks good.

Only comment/concern: the main content space currently receives a column span of 9; we can go up to 12, right?

Due to this, and the existing shift of 1 column, we have a fairly large gap now between the main content column and the right aside navbar — do we want to shorten the width of this gap a bit?

We could also tackle `DESIGN-206` as part of this branch fairly easily?

**Comment by klepas** [comment]
@petronbot I think your code example above is missing the class? ;)

We need to add some documentation around this, but otherwise, this branch LGTM.

**Comment by klepas** [comment]
> I couldn't actually think of the appropriate place to document it. I thought maybe when we're documenting a Controls/Filters sidebar sometime in the future that's when we'd explain how to use this class? Until then it's undocumented?

I’d place this in the grid section; we can just refer to that, despite it not being in the grids partial.

I think we definitely need to document this.

**Comment by klepas** [comment]
> Good call - we'll have to update the images there documenting the default grid layout too.

Ah, good point.

@hannah-ustwo could you help us? (:

@petronbot I reckon Jools would be able to help us in updating the documentation to cover this — reckon we should do a hangout tomorrow?

**Comment by joolswood** [comment]
Yeah happy to help out. When you say Controls/Filters @petronbot this is independent of the Controls Bar right?

**Comment by klepas** [comment]
> When you say Controls/Filters @petronbot this is independent of the Controls Bar right?

Yup. One is a header controls bar, the other is a left hand aside nav sidebar.

**Comment by klepas** [comment]
`DESIGN-203` covers the missing documentation on the `.controls` bar; we’re gonna merge this branch once the left | right aside navbar rework & documentation is complete. :)

**Comment by klepas** [comment]
Immmma be mergin mateys — RH-sidebar incoming! :D

**Pull request merged**
