### PR TITLE
Feature - Offset list style

### PR DESCRIPTION
**Pull request by simonschwartz**
## Description

This PR proposes a possible way of styling list items where the title is offset from the body content of the list item. This list style allows users to quickly scan the heading of list items on a page. 

These styles are currently in use on the Australian Numbers page. This page is a list information about important Australian phone numbers.
## References

GOVAU-322 - Agency team Jira ticket
#270 - UI Kit GitHub issue
## Additional information

australian-numbers
## Definition of Done
- [ ] Content/documentation reviewed by Julian or someone in the Content Team
- [ ] UX reviewed by Gary or someone the Design team
- [ ] Code reviewed by one of the core developers
- [ ] Acceptance Testing
  - [x] Cross-browser tested against standard browser matrix (TBD)
  - [ ] Tested on multiple devices (TBD)
  - [x] HTML5 validation (CircleCI)
  - [x] Accessibility testing & WCAG2 compliance (`npm test`)
- [ ] Stakeholder/PO review
- [ ] CHANGELOG updated

### CODE REVIEW

**Comment by klepas** [comment]
I can pick up the review of this @simonschwartz.

**Comment by klepas** [comment]
I made some edits to do 2 main things:
- moved the `article` wrapper one tier higher, now wrapping the headings too (those got placed inside a `header`)
- moved all of `.list-horizontal` from flexboxes to `span-column()`

I tested it in IE8, 9, and 10: looking all good, and works just as before in IE8 (bit borked).

Only downside I’ve found: the ‘left-padded’ horizontal list item (last horizontal list style example, where the `figure` is empty) does not expand the empty `figure`. Previously flexbox still gave this empty item a width… anyone got any easy fixes?

I haven’t come up with a better class name yet… I had a chat with Simon and we thought of something like a Swiss variant of the horizontal list… but that’s still all rather presentational, and not descriptive of the content itself?

**Comment by simonschwartz** [comment]
Thanks for reviewing this for me @klepas All those changes look great to me :)

**Comment by joolswood** [comment]
Hey @klepas from a content perspective, as far as I can see, it's just coming to an agreement on the class name and adjusting the doco right?

I might just make a change to the example so people don't think they have to do the giant numbers/highlighted style.

I'm not sure why this file is in there though `ssets/sass/templates/highlight.hbs` - I can't see it showing up anywhere, even in the zoo page?

WRT to the class name, some options:
1. Keep as 'offset item' \ `offset-item` `offset-title` `offset-body` - it's not super obvious what it does.
2. How about 'Split title & body item' describing `<li class="split-list-item">`, `<header class="item-title">`& `<div class="item-body">` - can you guys consider if this might trip us up down the track, I'm wondering about the word `split` in particular.
3. GOV.UK style uses something like `floating-children` - I'm not a big fan of this for obvious reasons.

**Comment by klepas** [comment]
I’ve rebased this branch, pulling in some of the other edits in the lists partial that came across from the design tweak branch.

Things left to do:
- discuss this feature with Agency team to get clarity into usage
- devise appropriate class names
- devise some documentation
- final code review post rebase

**Comment by klepas** [comment]
I’ve scheduled some time to talk to Michael from Agency about this.

**Comment by klepas** [comment]
@simonschwartz @maxious fyi—

Had a chat with Michael and Alz about this feature with a few outcomes:
- not fully clear what the feature will be used for;
- consequently, markup is hard to figure out —  a list of headings with some content each wrapped in an `article` (what happens if this list is used inside an existing `article`?) vs definition lists a la glossary style (which would be a variant of the `<dl>`), etc.
- feature is not yet tested properly and is likely to change

Given this, and the fact that Sites needs to provide editorial support for this feature we decided to leave this as custom CSS (soz for the tech debt Alex) with Sites for now until the feature matures.

Bugger.

Closing PR.

**Pull request closed without merging**
