### PR TITLE
Hidden class that works with screen-readers

### PR DESCRIPTION
**Pull request by jonathanconway**
Could we look at adding a class, say `a11-hidden`, in order to hide elements that are structural or contextual?

E.g. contextual text that would be read out by a screen-reader, but wouldn't need to be shown visually.

WebAIM provides guidance on [techniques for hiding text](http://webaim.org/techniques/css/invisiblecontent/#techniques), so I've based this implementation off it.

### CODE REVIEW

**Comment by TrebBrennan** [comment]
@jonathanconway we have one in the pipe-line waiting for a merge:
https://github.com/AusDTO/gov-au-ui-kit/pull/208/files#diff-b6ebf178f828b075f2e755f2db5324cbR8

**Comment by jonathanconway** [comment]
Ah sweet!

**Comment by klepas** [comment]
I’m gonna close this since this feature request is covered by the other PR.

Thanks for raising it though — points out that we should be more specific with our PRs maybe and not have buried features in them that aren’t noted (I do this all the time… :S).

**Comment by jonathanconway** [comment]
No no, all good!

I might just do issues first before PRs, just to see if it hasn’t already been done.

Thanks!

Cheers,

Jonathan Conway

**Pull request closed without merging**
