### PR TITLE
Applies font-size 1em to complex content items within table tds.

### PR DESCRIPTION
**Pull request by klepas**
## Description

Applies @TrebBrennan’s fix from #417. I played around with the font sizing — applying font-sizing via the Bourbon `rem()` does not override the specificity set, so using `1em`.

Should fix for #417.
## Definition of Done
- [x] Code reviewed by one of the core developers
- [x] Acceptance Testing
  - [x] HTML5 validation (CircleCI)
- [x] Stakeholder/PO review
- [x] CHANGELOG updated

### CODE REVIEW

**Comment by klepas** [comment]
@TrebBrennan Hey, if you get a sec, chance you could take a quick squiz at this? I basically just implemented your fix after realising I’d have to change too much else around. Thoughts?

**Comment by klepas** [comment]
Had a chat with @TrebBrennan and he pointed out we have graceful fix: because we only ever gave font sizes directly to content items like `ul`, `ol`, `p`, etc., we can move these to `body { … }` and thus avoid having to code font sizing resets elsewhere.

This PR does that now.

The only pain point I can think of: peeps who implemented uikit and extended it with their own SASS that do font-sizing overrides, akin to the one that I was about to apply to `table` > `td` > `p`/`ul`/…

Anyone have any concerns?— @jonathanconway @elisechant @nathf @TrebBrennan ? :)

**Comment by jonathanconway** [comment]
@klepas All good from my end. We've dropped all custom styling in identity-idp. When we re-do it, we'll be using the latest version of UI-Kit, which should include this PR.

**Comment by klepas** [comment]
Thanks @jonathanconway.

**Comment by TrebBrennan** [comment]
LGTM, thanks for that :)

**Pull request merged**
