### PR TITLE
Feature/DESIGN 116 lists content

### PR DESCRIPTION
**Pull request by joolswood**
Hi @TrebBrennan hopefully this doesn’t cause headaches - here’s the latest from my branch.

### CODE REVIEW

**Comment by maxious** [comment]
https://github.com/AusDTO/gov-au-ui-kit/pull/107/commits/f601472ab6d74d86a3cabd05ca1efee3b893fc86 probably the difference?

**Comment by joolswood** [comment]
Hey @maxious thanks for the fix https://github.com/AusDTO/gov-au-ui-kit/pull/107/commits/ecbbf0a5f44f9987703b726362ccb9f4eb04bcad  But given the number of problems with trying to merge this branch, maybe I should just do a commit of https://github.com/AusDTO/gov-au-ui-kit/pull/107/commits/f601472ab6d74d86a3cabd05ca1efee3b893fc86 straight to `feature/DESIGN-116_lists` ?

**Comment by maxious** [comment]
that would be good :)

**Comment by joolswood** [comment]
@maxious on it

**Pull request closed without merging**
