### PR TITLE
Compile icons to a seperate css file as well

### PR DESCRIPTION
**Pull request by maxious**
## Description

Compile icons to a seperate css file as well. That way, down stream users who want to hack on the current merged SCSS can still include this CSS after to have pretty inline icons.
## Additional information

I also minified all the CSS which is mostly useless for the icons file but at least it's consistent.

### CODE REVIEW

**Comment by klepas** [comment]
We need to dedicate some energy down the line into icons properly; also related: building an installer wrapper… In the meantime, this looks like a good way of getting an icon scss file out into the assets dir.

@maxious is there a need on your end/Sites, or elsewhere, to do this currently? If so, happy to merge.

**Comment by maxious** [comment]
Yes we will use this in production for now, I'll merge then.

**Comment by klepas** [comment]
@maxious Hey, can you document this in the changelog please? :)

**Comment by maxious** [comment]
Isn't it better to leave this as undocumented-hack-please-do-not-rely-on-so-we-can-change-without-calling-a-breaking-change? :P

**Comment by klepas** [comment]
I think it should go into the changelog, and chuck an `[experimental]` and `[undocumented]` flag on it, at least for our benefit? (imho)

**Pull request merged**
