### PR TITLE
Added a new links partial

### PR DESCRIPTION
**Pull request by hannah-ustwo**
## Description

Restyled the existing links for visual polish and accessibility and pulled it all into a new separate link partial. Created a color mixin that should be sustainable and defineable by block element. Currently, this commit is defining link styling within
- `.content-main`
- `footer`
- `.govau—header`
- `hero`

Additionally, there is an independent class `.templink` created for
inactive link placeholders (which GOV.AU will have a LOT of in its beta)

This branch is currently missing the following, but has been done on a separate branch by @klepas :
- "See more >" link
- Tags
- External link

Last but not least, this needs to be wrapped up with documentation by @joolswood.

### CODE REVIEW

**Comment by klepas** [comment]
I’ll pick this up today.

**Comment by joolswood** [comment]
Roger

**Comment by klepas** [comment]
Updated the branch with new features, and tried bugfixing the header button and inverted `:hover` and `:focus` issues.

I’ve just quickly dumped out some screenshots for a variety of link issues that are left—

## “Menu” text for the expandable/collapsible primary nav hamburger

Current focus:
screen shot 2016-07-22 at 2 17 25 pm

Current hover:
screen shot 2016-07-22 at 5 30 53 pm

## Button hover & focus consistency

screen shot 2016-07-22 at 5 28 05 pm

screen shot 2016-07-22 at 5 28 08 pm

## List view tag cloud hover/focus is ugly & inconsistent

screen shot 2016-07-22 at 5 28 27 pm

screen shot 2016-07-22 at 5 28 33 pm

## Control bar general links have no diffs for hover

screen shot 2016-07-22 at 5 31 02 pm

## Local/sidebar nav example hover styling is off in the styleguide?

screen shot 2016-07-22 at 5 31 59 pm

## Button styles on `examples/index.html` off

screen shot 2016-07-22 at 5 31 30 pm

**Comment by klepas** [comment]
Build of the new section in the styleguide, and for inception-testing:

https://768-59086769-gh.circle-artifacts.com/0//home/ubuntu/gov-au-ui-kit/build/section-links-anchors.html

^_^

**Comment by klepas** [comment]
Reviewed up to and inc. `76bbeb2`. Very clean. (:

**Comment by klepas** [comment]
> We've got a specificity problem there.

@petronbot Yea. What do you think about consolidating the `_buttons.scss` and `_links.scss` to fix it?

**Pull request merged**
