### PR TITLE
Bugfix/typography edit

### PR DESCRIPTION
**Pull request by joolswood**
## Description

Rework of typography content for clarity.
## Additional information

@klepas @TrebBrennan both of you should probably take a look (Treb - especially for checking for clarity of Spacing section edit)

### CODE REVIEW

**Comment by klepas** [comment]
@joolswood I had a review, and made some amendments, largely on technical points. Please take a quick look over the edits re. my phrasing/language, etc.

Happy to clarify on any points if needed.

Other than that, I consider this to be a nice improvement of our typography section — LGTM. (:

**Comment by klepas** [comment]
LGTM.

**Comment by joolswood** [comment]
## Definition of Done
- [x] Content/documentation reviewed by Julian or someone in the Content Team
- [x] UX reviewed by Gary or someone the Design team (clean up of content only, no change to UI-Kit code)
- [X] Code reviewed by one of the core developers
- [x] Acceptance Testing
  - [ ] ~~Cross-browser tested against standard browser matrix (TBD)~~
  - [ ] ~~Tested on multiple devices (TBD)~~
  - [X] HTML5 validation (CircleCI)
  - [X] Accessibility testing & WCAG2 compliance (manual/auto TBD)
- [x] Stakeholder/PO review - @hannah-ustwo do you want to take a look at this?
- [x] CHANGELOG updated

**Comment by hannah-ustwo** [comment]
All reads good to me. I wasn't too close into the type changes that happened here, but from what I've seen and read it all makes sense. Carry on!

**Comment by klepas** [comment]
Will merge once ci finishes.

**Pull request merged**
