### PR TITLE
Fixes html ol inside ul validation error.

### PR DESCRIPTION
**Pull request by klepas**
Learned something new about HTML. >__<

### CODE REVIEW

**Comment by maxious** [comment]
This adds a bullet point:

**Comment by klepas** [comment]
Ugh. Lol. I’ll fix this.

**Comment by klepas** [comment]
So embarrassing…

**Comment by klepas** [comment]
Err.

NEVERMIND ME.

I’m going to hide under a rock now.

**Comment by maxious** [comment]
NOTABUG

**Pull request closed without merging**
