### PR TITLE
New accordion style

### PR DESCRIPTION
**Pull request by hannah-ustwo**
## Description

Accordion styles have been revisited so that it is now possible to create new accordion styles scalably with a `@mixin accordion-styles`. The default accordion style through the use of the `<details>` tag is updated to match latest designs from GOV.AU (grey background). A new class `.accordion-forms` has been created to style accordions used for the filter widget and other form-related UI (blue background).
## Additional information

Default with no class
image

With class `.accordion-forms`
image
## Definition of Done
- [ ] Content/documentation reviewed by Julian or someone in the Content Team
- [x] UX reviewed by Gary or someone the Design team
- [ ] Code reviewed by one of the core developers
- [x] Acceptance Testing
  - [x] Cross-browser tested against standard browser matrix (TBD)
  - [x] Tested on multiple devices (TBD)
  - [x] HTML5 validation (CircleCI)
  - [x] Accessibility testing & WCAG2 compliance (`node test/pa11y.js`)
- [x] Stakeholder/PO review
- [x] CHANGELOG updated

### CODE REVIEW

**Comment by hannah-ustwo** [comment]
Still have the following left to do...
- Have the code reviewed before I start making any markup changes...code quality, naming conventions, etc. Looking to you @petronbot @klepas.
- Update markup throughout ui-kit to reflect the appropriate classes into any existing accordions we have in the ui-kit, i.e. our visual examples.

Also should note - in the current setup makes it so that a `detail` tag with no class looks kind of broken. That doesn't seem kosher to **require** a class for a tag, does it?  Should we perhaps choose one of the two styles, `.accordion-content` or `.accordion-forms`, to be the default?  I'll  adjust accordingly.

**Comment by hannah-ustwo** [comment]
Updated so that `<details>` does not need a class.  `.accordions-content` class is GONE!

`<details>` with no class looks like this

image

**Comment by hannah-ustwo** [comment]
Ready for your review @petronbot @klepas

**Comment by TrebBrennan** [comment]
JS doesn't seem to work in IE8. Recored this as a bug ticket but it should be okay for now given our current levels of support.

**Comment by joolswood** [comment]
Working in a local branch on some content at the moment.

**Pull request closed without merging**
