### PR TITLE
Update the name of our Slack channel

### PR DESCRIPTION
**Pull request by petronbot**
## Description

Our channel name on Slack has changed, so they should be updated in UI Kit docs as well.
## Definition of Done
- [x] Content/documentation reviewed by Julian or someone in the Content Team
- [x] Code reviewed by one of the core developers
- [x] Stakeholder/PO review
- [x] CHANGELOG updated

### CODE REVIEW

**Comment by klepas** [comment]
LGTM.

**Comment by klepas** [comment]
@petronbot Nah yea, let’s merge; looks fine to me ^_^

**Comment by klepas** [comment]
@joolswood Can I merge?

**Comment by joolswood** [comment]
@klepas LGTM

**Pull request merged**
