### PR TITLE
Accordions

### PR DESCRIPTION
**Pull request by klepas**
## Description

This adds accordions via `<detail>` and `<summary>` with support to use divs. It’s mostly complete, but needs a few more things…

This branch also holds a number of other items not really related to the accordions (sorry :S), including:
- adds `$lighter-aqua`
- fixes/re-aligns left padding/margin for generic content `li` (was changed in the last sprint and was out of alignment with quotes, def. lists, callouts, etc. 
- separates styling for `img` into it’s own partial
- adds responsive video support for `embed`, `object`, and `iframe`
- adds styling for `kbd` elements, inc. documentation (within the typography partial — needs reordering though)
- changes the background colour for `blockquote` from `$lighter-grey` to `$non-white`
## Additional information

Things left to do:
- check over ARIA roles
- sprinkle with some JS love add/remove the `open` attribute
- some more testing
- check over `:focus` and `:hover` styling
- test a group of the accordions together, and how they interact (open/close of multiple items)
- consider using definition lists over divs?
- documentation and usage guidelines

The current example of the accordion lives inside `examples/index.html`.

Please review and discuss to complete! ^_^

### CODE REVIEW

**Comment by klepas** [comment]
Reminder to self: add the final stuff to the changelog.

**Comment by TrebBrennan** [comment]
@petronbot
There is an `open` attribute on the `details` tag which hangs around when closed... I think the default behaviour of `details` is to remove that so we might need to address that with our JS overrides?

**Comment by klepas** [comment]
Possibly nagging question: prospects for including expand/collapse all toggle links at the top of a series of accordions? :S

**Comment by klepas** [comment]
@petronbot 

> Prospects are good, it's in the backlog as a separate story though. Do you think we should hold back this feature until it includes expand/collapse all?

IMHO, we should not roll out this feature w/o expand/collapse all.

**Pull request merged**
