### PR TITLE
Accessibility notes per-feature

### PR DESCRIPTION
**Pull request by TrebBrennan**
# Accessibility test notes for each feature
## Description

As a user of the guide, at any time, I can understand the level of accessibility compliance offered by any component.
## Definition of Done
- [x] Content/documentation reviewed by Julian or someone in the Content Team
- [x] UX reviewed by Gary or someone the Design team
- [x] Code reviewed by one of the core developers
- [x] Acceptance Testing
  - [x] HTML5 validation (CircleCI)
- [x] Stakeholder/PO review

Not sure if this should live in every feature, it seems a bit over the
top? But maybe it just seems weird right now while all the features
have the same level of testing done?

---

### CODE REVIEW

**Comment by klepas** [comment]
### Suggested edits
- Rename accordion label to “Accessibility compliance information”
- Add a11y accordion to each set of tables in the Tables section (not just last item)
- Add a11y accordion to various components in the Typography section

### Questions

Does it make sense to add the accessibility accordion thing to the Grid section? It’s not obvious to me what was tested here.

---

Otherwise, LGTM.

**Comment by joolswood** [comment]
Hey @klepas some for your points might be addressed by my commit.

**Comment by klepas** [comment]
LGTM.

**Comment by klepas** [comment]
Mergin’.

**Pull request merged**
