### PR TITLE
Include the GA snippet in the Guide template

### PR DESCRIPTION
**Pull request by petronbot**
- Included GA snippet
- Added link in footer to DTO Privacy Statement
- Added link to the licence in footer

### CODE REVIEW

**Comment by klepas** [comment]
LGTM.

**Comment by TrebBrennan** [comment]
+1
This seems to address the need.

**Comment by klepas** [comment]
Let’s link to `LICENSE` in the footer too? (It’s sadly missing from the build output — the `*.md` files are included currently).

Other than that, LGTM.

**Comment by klepas** [comment]
LGTM.

**Pull request merged**
