### PR TITLE
Feature/Design 106 browser notification

### PR DESCRIPTION
**Pull request by TrebBrennan**
## Definition of Done
- [x] Content/documentation reviewed by Julian or someone in the Content Team
- [x] UX reviewed by Gary or someone the Design team
- [x] Code reviewed by one of the core developers
- [x] Acceptance Testing
  - [x] Cross-browser tested ie8/9
  - [x] HTML5 validation (CircleCI)
- [x] Stakeholder/PO review
- [x] CHANGELOG updated

### CODE REVIEW

**Comment by TrebBrennan** [comment]
##NOTE
This is just for private-demo and is not the intended wording or solution for Beta

ie8_vs_ie9_demo

**Comment by klepas** [comment]
Happy to review this this moin, unless you beat me to it @petronbot.

**Comment by klepas** [comment]
Just reviewed this. LGTM. I’m going to rebase to pull in `examples/layouts/default.html` and put all the script stuff in there. (:

**Comment by klepas** [comment]
Just did a rebase to move all this stuff into `examples/layouts/default.html`, keeping this IE conditional stuff all in there. (:

I just did a test post rebase:
- builds fine
- no further a11y errors (just the 5 in the KSS forms page we know about)
- works as intended on IE9 (just the existing visual bugs)
- works as intended on ≤IE9: sans styling, except the yellow `.ua-notification` bar.

Should be ready to merge once ci tests finish.

**Comment by klepas** [comment]
Should be ready for mergin now — added a changelog and ci checks passed.

**Comment by klepas** [comment]
Mergin in Treb’s absence ^_^

**Pull request merged**
