### PR TITLE
Change calendar table example

### PR DESCRIPTION
**Pull request by joolswood**
## Description

Change of the `table-calendar.hbs` example to something more familiar/common. Also a few small fixes to the content in `_tables.scss` partial.
## Definition of Done
- [X] Content/documentation reviewed by Julian or someone in the Content Team
- [x] UX reviewed by Gary or someone the Design team @TrebBrennan 
- [ ] Code reviewed by one of the core developers - @klepas or @petronbot ?
- [X] Acceptance Testing
  - [x] HTML5 validation (CircleCI)
  - [x] Accessibility testing & WCAG2 compliance (manual/auto TBD)
- [x] Stakeholder/PO review
- [ ] CHANGELOG updated

### CODE REVIEW

**Comment by TrebBrennan** [comment]
@joolswood Let's have a quick chat about "Table with a caption" as there is a bit more to that example than just an added `<caption>`
`<thead>`
`<th scope="row">`

**Comment by joolswood** [comment]
Sure @TrebBrennan I noticed that it had changed - I don't know why.

**Comment by joolswood** [comment]
Libby happened to hear when we discussion this PR and supported the change. Can we resolve the table with a caption issue soon @TrebBrennan and then pull this.

**Comment by joolswood** [comment]
Hey @TrebBrennan back over to you.

**Comment by klepas** [comment]
LGTM.

Logged edits to changelog.

Will merge. (:

**Pull request merged**
