### PR TITLE
Add shaded list

### PR DESCRIPTION
**Pull request by simonschwartz**
## Description

The shaded list is an extension of the horizontal list. It appears on Daylight savings and School holiday pages on gov.au
## Additional information

shaded-list
## Definition of Done
- [ ] Content/documentation reviewed by Julian or someone in the Content Team
- [ ] UX reviewed by Gary or someone the Design team
- [ ] Code reviewed by one of the core developers
- [ ] Acceptance Testing
  - [ ] Cross-browser tested against standard browser matrix (TBD)
  - [ ] Tested on multiple devices (TBD)
  - [ ] HTML5 validation (CircleCI)
  - [ ] Accessibility testing & WCAG2 compliance (manual/auto TBD)
- [ ] Stakeholder/PO review
- [ ] CHANGELOG updated

### CODE REVIEW

**Comment by hannah-ustwo** [comment]
[STATUS UPDATE - Addressing soon] This was deprioritized for the Aug 4th demo and was put on hold for UI-kit. With newly-established priorities to remove custom CSS from platform for August 30th, this will be addressed by UI-kit in one of the upcoming 3 sprints (32, 33, or 34) leading up to private beta. (woot)

**Comment by hannah-ustwo** [comment]
Correcting previous statement - As this is a new feature and with testing and debugging for cross-browser compatibility being of utmost priority for Aug 30, this will likely be addressed by UI-kit post Sprint 34.

**Comment by klepas** [comment]
@simonschwartz @hannah-ustwo Just as wiht #209, I wanted to revisit this PR — should we close and re-implement from a more recent state of `develop`?

**Comment by klepas** [comment]
Closing.

**Pull request closed without merging**
