### PR TITLE
Numbered lists

### PR DESCRIPTION
**Pull request by jonathanconway**
# Numbered lists with circle styling

screen shot 2016-08-09 at 11 10 46 am

Uses [CSS Counters](http://www.w3schools.com/css/css_counters.asp), which seems to have [reasonable browser support](http://caniuse.com/#feat=css-counters).

### CODE REVIEW

**Comment by TrebBrennan** [comment]
Hey @jonathanconway thanks for contributing.

We try not add features to the our releases which don't have accompanying documentation; if you can you provide some more information for us when this style should be used and what it achieves that a normal `<ol>` doesn't we'll be better placed to work out where it goes etc. :)

**Comment by jonathanconway** [comment]
Never mind, just found out that [ordered lists have already been implemented](https://gov-au-ui-kit.apps.staging.digital.gov.au/section-typography.html#guide-typography-4-lists).

Closing this.

**Comment by TrebBrennan** [comment]
Sure, ours are much more vanilla than yours, so if there is a user need which requires your more visually prominent ones let us know. 👍

**Comment by jonathanconway** [comment]
I talked to one of our IxDs and he said it was a very quick design and not considered to be a user need at present, so I'm happy to go with the current vanilla one until the situation changes.

In future I'll check with the IxDs about these kinds of things before making a PR.

**Pull request closed without merging**
