### PR TITLE
Feature/data export

### PR DESCRIPTION
**Pull request by klepas**
## Description

Work by Petra that adds a new gulp task `styleguide.data` and edited with help by @bjgordon to generate a JSON file of all our SASS comments (using `kss.traverse`).

This JSON file is then loaded in the new `dto-design-guide` repo where we want to load it into Jekyll and other content.
## Definition of Done
- [x] Code reviewed by one of the core developers
- [x] Acceptance Testing
  - [x] HTML5 validation (CircleCI)
  - [x] Accessibility testing & WCAG2 compliance (`npm test`)
- [x] Stakeholder/PO review
- [x] CHANGELOG updated

### CODE REVIEW

**Comment by klepas** [comment]
The `examples` gulp task is broken at the moment in this branch, and is blocking merging. Will investigate.

**Comment by klepas** [comment]
Re-added `gulp-compile-handlebars` to fix the `examples` gulp task — CI should be happy now.

**Comment by klepas** [comment]
@danwhitmarsh Heya, could you review this for me?

Jools and I need this merged into develop for us to proceed doing refactoring work on the guidance that is currently still all held in the SASS as comments.

I had to re-add a few dependencies that @petronbot removed so that the `build.prod` task didn’t error out (just stuff to do with our old and now somewhat deprecated gov.au example html files we were compiling out of handlebar `.hbs` files).

I get local issues doing a `build.prod` due to phantomjs, but CI seems happy.

**Comment by klepas** [comment]
@danwhitmarsh Hey, could you review this for us? :)

**Review by danwhitmarsh — APPROVED** [review]

**Pull request merged**
