### PR TITLE
Bugflix/design 231 accordions doco

### PR DESCRIPTION
**Pull request by joolswood**
Initial edit of the accordion content.

Please review @klepas or @petronbot for anything egregious, or just typos!

### CODE REVIEW

**Comment by klepas** [comment]
@joolswood Nice. I had this idea of grouping, and then splitting up the guidance of bullet points under the **Usability** heading, something like this (uses `h3` to split under that heading in this eg) — what do you think?

screen shot 2016-07-22 at 9 07 50 pm

**Comment by joolswood** [comment]
It's an idea. If my edits of the content under usability are ok it might be an overkill to add headings again (there are fewer bullet points now), and I'm not sure they fit so neatly between the 2 (the same user might well be going from designing and implementing and back again).

I think it probably means we haven't the overall content in that section quite right :)

**Comment by klepas** [comment]
@joolswood I used headings after just separating the list out and leading each list with a `p` string like “When designing:”, or “When implementing:”, and noticed headings padded it visually out further.

I’m chill.

I’d pref. to see the list ordering (despite being a `ul`) to group the design / writing and tech / template mark stuff together? (:

**Comment by klepas** [comment]
I’ve updated this.

@petronbot Reckon we merge this and iterate further, or wait on @joolswood for this one?

Usability section now looks like:

screen shot 2016-07-25 at 10 07 05 am

**Comment by joolswood** [comment]
👍

**Pull request merged**
