### PR TITLE
Style phone number inputs

### PR DESCRIPTION
**Pull request by jonathanconway**
image

### CODE REVIEW

**Comment by klepas** [comment]
LGTM. Thanks @jonathanconway 

I see no compatibility issues here either with older browsers — from what I understand any unsupported types will revert to the `type='text'`.

@petronbot: I say merge? :)

**Comment by klepas** [comment]
Housekeeping:
- [ ] possibly discuss hint text (& the requested format of the number, eg. inc. ‘+61’, …)
- [ ] document anything as applicable
- [ ] update changelog

**Comment by jonathanconway** [comment]
Good points, @klepas.

# Hint text

Service NSW show an area code dropdown and dummy mobile number:

image

I can't see why we'd ever have a non-Australian mobile number though.

So my suggestion is just to have something like this:

> For example: 0412 345 678

**Comment by klepas** [comment]
> I can't see why we'd ever have a non-Australian mobile number though.

Neither, but I could see this changing, though that’s something we can tackle when it occurs.

---

Regarding hint text, there have been some recent discussions in adding/extending the styleguide examples with various a11y features to make fully-fledged examples, and not just really stripped-down examples. Example:
- we might have an anchor with a `rel='help'` — it might seem natural to document this under a section called ‘Links and anchors’;
- we have a _Forms_ section in the guide;
- we should not just documented the `help` anchor under _Links and anchors_, but also within a fully-fledged forms example that includes not just hint text, `label`, but also one with a `help` anchor (could lead to another resource, or load a JS-powered mini popup providing guidance to the user)

I think we should consider doing this therefore even for these examples. @hannah-ustwo, @TrebBrennan and @petronbot what do you think?

**Comment by klepas** [comment]
For reference, I ended up just doing a copy-pasta on a further along branch of the forms partial.

It’s covered in PR #204; closing this PR subsequently.

**Pull request closed without merging**
