### PR TITLE
Bugfix/design 230 nav doco

### PR DESCRIPTION
**Pull request by joolswood**
Here’s my re-work of the doco on navigation. Please can @klepas or @petronbot review to check I haven’t removed anything vital in cutting it back, or any silly typos.

### CODE REVIEW

**Comment by klepas** [comment]
LGTM! Really nice cleanup of the page @joolswood.. I say merge.

**Comment by klepas** [comment]
I’m making some edits to the structure — the a11y section is technically the parent of the Skip Links, but since our Index links don’t disambiguate the two stylistically I’m gonna edit this to match our current other pages.

**Comment by klepas** [comment]
Also:

screen shot 2016-07-25 at 4 09 09 pm

**Comment by klepas** [comment]
OK, so i think this is mergeable now… with 3 points of concern:
- [ ] check post-merge that our local nav changes from @TrebBrennan are as they should be
- [ ] update documentation for local nav (namely `.is-active` -> `.active`, and introduction of `.current`)
- [ ] fix possible page footer overflow bug

**Comment by klepas** [comment]
@petronbot what do you reckon?

**Comment by klepas** [comment]
> Cool - I'm happy as long as these are consistent. How about .is-active and .is-active-parent? I'm fond of .is- for a class that describes state but what do you think @klepas?

I found `.is-active` more descriptive.

> Should 'Footer navigation' live in Navigation or Footer (navigation)?

At the moment I’m keen to leave it where it is, but something I could see removing out into its own _§ Footer_ and _§ Header_, respectively.

**Comment by joolswood** [comment]
Just spotted an issue (well, a couple) with the skip link example:
screen shot 2016-07-26 at 10 12 39 am

**Comment by joolswood** [comment]
UPDATE: @klepas just explained what was going on with this, he's going to do some work with the styling.

Nope @petronbot:
- the example itself isn't in the Example box
- and the bullet points, which were previously part of the example, are now sitting outside of the example.

I can probably work on this one myself, but didn't want to overwrite any subsequent decisions made about how this example was going to work...

**Comment by klepas** [comment]
LGTM. Mergin. (:

Reminder to us: if @TrebBrennan updates the classes for the local nav we need to update the _§ Navigation_ documentation again before we release — no biggie, but worth noting.

**Pull request merged**
