### PR TITLE
Header: Controls bar

### PR DESCRIPTION
**Pull request by TrebBrennan**
New feature Admin Control Bar.
Support for Admin context in future work (.admin on body)

### CODE REVIEW

**Comment by klepas** [comment]
Nice.

Only feedback thoughts from me atm are re. the naming of the classes — we have `.controls` already (which was the most open class name I could come up with for general Sites admin controls at the time)… now we have `.admin` and `.admin-bar`.

We should also try to stick with our BEM conventions.

**Comment by TrebBrennan** [comment]
Yeah awesome. Any code I'm producing is just suggestions please don't feel like it needs to be merged verbatim, it's much less my area of expertise :)

We have two things that are similar.
1. Context/Nav for a admin user 
2. Context/Nav for a public user [not used yet just planned for]

I was thinking we could use `.admin` for 1, and `.controls` for 2; but I'm not wedded to any of that.

Happy to take your advice on the BEM conventions. 👍 

@klepas you mind reviewing the HTML? I feel like there is probably a more semantic solution to this widget?

**Comment by klepas** [comment]
@TrebBrennan —

> @klepas you mind reviewing the HTML? I feel like there is probably a more semantic solution to this widget?

Will do.

**Comment by maxious** [comment]
Please document somewhere.

**Comment by klepas** [comment]
I think this won’t make it into this afternoon’s release… I hope that’s OK for anyone concerned? :S

**Comment by klepas** [comment]
I’ll do a review of this if you like. (:

**Comment by klepas** [comment]
Had a few thoughts—
1. What do you think about switching to flex boxes and margin auto to manage the left | right alignment of content for this controls bar? It seems like a simpler way to do the alignment (maybe)?
2. I think the edit button contextually might make more sense immediately to the right of the last breadcrumb item, since it would effectively be editing that page?
3. We have no specific hover styles set for the generic links.
4. Should we consider renaming the maroon colours to something more functional — controls inverted colour or something?

Otherwise, LGTM.

**Comment by klepas** [comment]
> I thought about using flex here, but thought that grid-columns would do the job since we're only accounting for '1 to 2' sections. If we want to add '1 to n' sections down the road we can iterate.

Sounds good.

> Good call, I've updated the styles so that the Breadcrumbs can sit inline with a button. The Controls bar needs a bit of love on a small screen - do you think that the breadcrumbs should be hidden here too?

Yes. I just checked w/ Dan on this, and he’s in agreement. In mbl portrait all that would remain then top left is the edit button.

(:

**Pull request merged**
