### PR TITLE
Adds basic page header & footer

### PR DESCRIPTION
**Pull request by klepas**
As noted in standup 10/6, was working on this.

IMPORTANT: This adds a class to the page header and footer respectively (`page-header` and `page-footer`). This is in part because I was targeting the page header and footer by their `role` (`banner` and `contentinfo`), which the linter didn’t like much.

This goes mostly off the gov.au header, and uses a similar design for the footer, lacking any footer designs.

We have 3 different header designs at the moment:
- gov.au
- Gary’s header design from the Sketch files
- Alzbeta’s header design for Comms&Arts.

Happy to iterate more.

As discussed, code needs a bit of refactoring to keep the partials organised and compliant to our conventions.

### CODE REVIEW

**Comment by klepas** [comment]
Hey. Missed these messages.

Agreed on both counts. I’ll finish up the header, and then footer, and I’ll update the linter config; I’ll remove the classes, and their markup.

I won’t try to clean or refactor anything far outside the scope of what I’m adding in this feature.

**Comment by klepas** [comment]
[Don’t merge this PR please.]

**Comment by klepas** [comment]
Note to self: double check role-based CSS targeting support.

**Comment by maxious** [comment]
I don't think browsers care that it is role, just any attribute that is not class/id http://caniuse.com/#feat=css-sel2

**Comment by klepas** [comment]
I renamed my branch to only cover the page header so that @petronbot can work on the footer in a separate feature branch.

**Pull request closed without merging**
