### PR TITLE
Remove `strong` from a11y accordion

### PR DESCRIPTION
**Pull request by joolswood**
## Description

The `strong` tag was causing problems with screenreader use of the a11y accordion.
## Additional information

Also updated 1 of the boxes to the current style, which slipped through.
## Definition of Done
- [ ] Content/documentation reviewed by Julian or someone in the Content Team
- [ ] Code reviewed by one of the core developers
- [x] Acceptance Testing
  - [x] HTML5 validation (CircleCI)
  - [X] Accessibility testing & WCAG2 compliance (`npm test`)
- [ ] Stakeholder/PO review
- [ ] CHANGELOG updated

### CODE REVIEW

**Comment by klepas** [comment]
@joolswood it was also the jargon-ised wording. I reckon we should try improve on it. I think we can avoid linking to the tools we use too, since we already point them out in the readme. Thoughts?

**Comment by joolswood** [comment]
@klepas let's work on this. I've been trying to hit a balance between plain English and keywords that aid scannability for main users. We can skew it more towards a general user, sure.

I think it's helpful to talk about specific tools with each component as we need to consider users coming straight to individual sections eg from Google. I feel like as there are multiple ways to do automated HTML5 validation and WCAG checking its important be crystal clear about how we did it, which may lead to repetition.

Happy to look at arguments against. Consistency in listing the tools everywhere is probably more important when we are more advanced in testing with specific components over others - not at the same level across the board.

**Comment by klepas** [comment]
@joolswood I had another crack at this. I’ve updated one of the accordions (in the accordions section) with this markup:

circleci artefact URL for the page: https://1370-59086769-gh.circle-artifacts.com/0//home/ubuntu/gov-au-ui-kit/build/section-accordions.html

```
<details data-label="accordions-accessibility" aria-expanded="false">
  <summary>Accessibility &amp; browser testing</summary>
  <div class="accordion-panel">
    <p>Passed:</p>
    <ul>
      <li>HTML5 validation (automated)</li>
      <li>WCAG:AA compliant (automated)</li>
    </ul>
    <p>Untested:</p>
    <ul>
      <li>WCAG:AA manual</li>
      <li>Browser support &mdash; automated and manual</li>
    </ul>
  </div>
</details>
```

What do you reckon?

**Comment by joolswood** [comment]
I'll take another look. We don't have a JIRA ticket yet for this, do we?

**Comment by joolswood** [comment]
Just added one (DESIGN-423) @klepas

**Comment by joolswood** [comment]
@klepas I don't want to slow stuff down too much so happy to keep working on this one in isolation, but my preference would be to do some IA strategic thinking about how we deal with browser support and accessibility levels across the guide (some related tickets DESIGN-469, DESIGN-471).

If we can assume a tag-based / module organisation of content, then maybe we can make the next work on these accordions start us off in that direction. I'm not saying spend ages on planning or code, but do some thinking about the common sections we want (like for instance, should we separate the accessibility and browser testing section; and do we want a 3rd section that shows the actual browser support for that item - kind of like a "Hey, this isn't the overall kit support level but we found out this actually works on Lynx etc.")

**Comment by klepas** [comment]
@joolswood Agreed that we should be thinking about how we can better include this info in an overhauled guide, post-KSS.

I guess for me the Q now is: do we make any edits here as proposed or do we leave this as until fairly soon when we ditch KSS?

**Comment by joolswood** [comment]
Guess we'll come back to this once we start refactoring content @klepas ?

**Comment by klepas** [comment]
Yup. I propose we close this branch, and do this as part of the refactoring work.

This is going to be one of those content blocks that we will want to retain inside the SASS directly — these things should reflect exactly what code we’ve tested and note its accessibility compliance and browser support therein (and not within the design guide)…

…and not in the format of an accordion. :D

IMHO, we should actually extend these as further custom fields that get pushed into the JSON, so that I can custom-build the layout for this data, eg by accessing like `{{ feature.wcag-complaince }}` etc. (because setting up the exact markup each time for each feature like this in the SASS, like we do right now is kinda dirty).

**Comment by klepas** [comment]
@joolswood Lemme know what you think — feel free to close this PR if you’re in agreement.

**Comment by joolswood** [comment]
I like this approach @klepas just hope we can get it to all hook together in Jekyll!

**Pull request closed without merging**
