### PR TITLE
Adjusted styling of disabled inputs

### PR DESCRIPTION
**Pull request by hannah-ustwo**
## Description

Addressing issue #166 Bug - Disabled input field is visually similar to default

Changed the disabled input to havea  2px dotted border at 25% opacity
## Additional information

v1
image

v2
image
## Definition of Done
- [ ] Content/documentation reviewed by Julian or someone in the Content Team
- [x] UX reviewed by Gary or someone the Design team
- [x] Code reviewed by one of the core developers
- [x] Acceptance Testing
  - [x] HTML5 validation (CircleCI)
- [x] Stakeholder/PO review
- [ ] CHANGELOG updated

### CODE REVIEW

**Comment by klepas** [comment]
Nice idea improving on the `disabled` style. I think we should look into applying a grey fill — commonly done on disabled UI fields?

**Comment by hannah-ustwo** [comment]
Good call on the grey @klepas, I'm committing another option with the filled grey and the same solid border as the other inputs, for accessibility reasons. I'm actually not feeling the dotted border...

image

**Comment by hannah-ustwo** [comment]
For consideration...Material Design's setup is lovely:
image

**Comment by klepas** [comment]
LGTM.

**Comment by TrebBrennan** [comment]
Reviewed in CircleCI build.

**Comment by klepas** [comment]
Tsk tsk, where’s the changelog update? :P

**Comment by TrebBrennan** [comment]
You didn't do that as part of the code review?

> Also LGTM. @TrebBrennan would you do a quick review and merge if you're happy?

:(

**Pull request merged**
